name: FreedomTelnet
main: me.StevenLawson.BukkitTelnet.BukkitTelnet
version: 4.4
description: Connect remotely to your server using any Telnet Client
authors: [bekvon, Madgeek1450, DarthSalamon, cowgomooo12, RobinGall2910]
